package com.resolvix.lib.collector.api;

import java.util.stream.Collector;
import java.util.function.Consumer;

/**
 * Defines the interface to an accumulator for a {@link Collector} of
 * one or more elements of a data set that forms two different views
 * of the input elements, using two separate {@link Collector}.
 *
 * @param <T> the input type
 *
 * @param <U> the output type generated by the first collector
 *
 * @param <V> the output type generated by the second collector
 */
public interface MatrixAccumulator<T, U, V>
    extends Consumer<T>
{

}
